#!/usr/bin/python3


def raise_exception_msg(message=""):
    """Raise for  a NameError exception with a message."""
    raise NameError(message)
